In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("edu.csv")

In [8]:
df = df.drop("Unnamed: 0",axis=1)

In [9]:
df.columns

Index(['기간', '구별', '원아수', '학급수', '학급당원아수', '초등학교', '학급수.1', '학급당학생수', '중학교',
       '학급수.2', '학급당학생수.1', '고등학교', '학급수.3', '학급당학생수.2'],
      dtype='object')

In [10]:
df = df.rename(columns={"초등학교":"초등학교수","학급수.1":"초등학급수","학급수.2":"중등학급수","학급수.3":"고등학급수"})

In [19]:
df = df.rename(columns={"학급당학생수":"학급당학생수(초등)","학급당학생수.1":"학급당학생수(중등)","학급당학생수.2":"학급당학생수(고등)"})

In [22]:
df

,기간,구별,원아수,학급수,학급당원아수,초등학교수,초등학급수,학급당학생수(초등),중학교,중등학급수,학급당학생수(중등),고등학교,고등학급수,학급당학생수(고등)
0,2018,종로구,"1,299",66,19.7,"5,507",277,19.9,"2,945",136,21.7,"10,016",373,26.9
1,2018,중구,"1,123",73,15.4,"5,226",246,21.2,"1,986",115,17.3,"7,539",291,25.9
2,2018,용산구,"1,574",79,19.9,"7,460",357,20.9,"3,753",169,22.2,"6,642",267,24.9
3,2018,성동구,"2,608",122,21.4,"11,922",585,20.4,"5,225",230,22.7,"5,939",251,23.7
4,2018,광진구,"3,050",137,22.3,"15,016",656,22.9,"7,564",304,24.9,"8,504",296,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2020,관악구,"2,991",196,15.3,"14,410",694,20.8,"7,124",308,23.1,"9,176",403,22.8
71,2020,서초구,"2,467",137,18.0,"22,668",880,25.8,"11,108",430,25.8,"9,804",390,25.1
72,2020,강남구,"3,260",181,18.0,"25,905",990,26.2,"15,602",555,28.1,"17,837",717,24.9
73,2020,송파구,"5,355",268,20.0,"31,373","1,406",22.3,"16,309",668,24.4,"14,537",607,23.9
74,2020,강동구,"4,237",208,20.4,"21,353",990,21.6,"10,064",425,23.7,"10,957",453,24.2

In [29]:
# df["초등학교수"] = df['초등학교수'].str.replace(",","").astype(int)
df["중학교"] = df['중학교'].str.replace(",","").astype(int)
df["고등학교"] = df['고등학교'].str.replace(",","").astype(int)

In [34]:
df["원아수"] = df['원아수'].str.replace(",","").astype(int)
df["초등학급수"] = df['초등학급수'].str.replace(",","").astype(int)

In [38]:
df = df.rename(columns={"초등학교수":"초등학교"})

In [40]:
df.to_csv("education.csv")

In [16]:
import pandas as pd
df = pd.read_csv("crime.csv")

In [17]:
df = df.rename(columns={"자치구":"구별","합계":"발생합계","합계.1":"검거합계","살인":"살인(발생)","살인.1":"살인(검거)","강도":"강도(발생)","강도.1":'강도(검거)',"강간강제추행":"추행(발생)","강간강제추행.1":"추행(검거)","절도":"절도(발생)","절도.1":"절도(검거)","폭력":"폭력(발생)","폭력.1":"폭력(검거)"})

In [18]:
df = df.drop(0)

In [19]:
df = df[df["구별"] != "합계"]

In [22]:
df = df.reset_index().drop("index",axis=1)

In [24]:
df["발생합계"] = df['발생합계'].str.replace(",","").astype(int)
df["검거합계"] = df['검거합계'].str.replace(",","").astype(int)
df["살인(발생)"] = df['살인(발생)'].str.replace(",","").astype(int)
df["살인(검거)"] = df['살인(검거)'].str.replace(",","").astype(int)
df["강도(발생)"] = df['강도(발생)'].str.replace(",","").astype(int)
df["강도(검거)"] = df['강도(검거)'].str.replace(",","").astype(int)
df["추행(발생)"] = df['추행(발생)'].str.replace(",","").astype(int)
df["추행(검거)"] = df['추행(검거)'].str.replace(",","").astype(int)
df["절도(발생)"] = df['절도(발생)'].str.replace(",","").astype(int)
df["절도(검거)"] = df['절도(검거)'].str.replace(",","").astype(int)
df["폭력(발생)"] = df['폭력(발생)'].str.replace(",","").astype(int)
df["폭력(검거)"] = df['폭력(검거)'].str.replace(",","").astype(int)

In [28]:
df.to_csv("crime2.csv")

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("doctor2.csv")

In [3]:
df = df.drop("Unnamed: 0",axis=1)

In [4]:
main_df = pd.read_csv("../pop.csv",index_col=0)

In [5]:
gwang = main_df[main_df['구별'] == "광진구"]

In [6]:
get = gwang[gwang["기간"].str.contains("2018")]['인구'].mean()

In [7]:
df = df[df['기간'].str.contains("2018")]

AttributeError: Can only use .str accessor with string values!

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      75 non-null     int64
 1   구별      75 non-null     object
 2   계       75 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.9+ KB

In [9]:
tar = df[df['구별']=='광진구']["계"]

In [10]:
(tar / get) * 100

4     1.195851
29    1.252257
54    1.293279
Name: 계, dtype: float64

In [11]:
df = pd.read_csv('../doc.csv',index_col=0)

In [12]:
df['기간'] = df['기간'].astype(str)

In [13]:
df = pd.read_csv('../pop.csv',index_col=0)

In [14]:
a = df[df["기간"].str.contains("2018")]

In [15]:
a[a['구별'] == '광진구']['인구'].mean()

370531.0

In [16]:
def doc_per_pop(doc, pop, city):
    doc['기간'] = doc['기간'].astype(str)
    years = doc['기간'].unique()
    li = []
    for year in years:
        df_doc = doc[doc['구별'] == city]
        doc_value = df_doc[df_doc['기간'] == str(year)]["계"].values
        te = pop[pop["기간"].str.contains(str(year))]
        pop_value = te[te['구별'] == str(city)]['인구'].mean()
        result = round((doc_value[0]/pop_value) * 100, 2)
        li.append([city, result])
    return li

In [17]:
doc = pd.read_csv("../doc.csv",index_col=0)

In [18]:
pop = pd.read_csv("../pop.csv",index_col=0)

In [19]:
doc

      기간   구별      계
0   2018  종로구   8704
1   2018   중구   4638
2   2018  용산구   2400
3   2018  성동구   3435
4   2018  광진구   4431
..   ...  ...    ...
70  2020  관악구   4190
71  2020  서초구  11452
72  2020  강남구  24595
73  2020  송파구  14407
74  2020  강동구   8657

[75 rows x 3 columns]

In [20]:
doc['기간'] = doc['기간'].astype(str)
df_doc = doc[doc['구별'] == "광진구"]
doc_value = df_doc[df_doc['기간'] == "2018"]["계"].values

In [21]:
doc_value[0]

4431

In [22]:
gw = doc_per_pop(doc,pop,'광진구')

In [23]:
gw

[['광진구', 1.2], ['광진구', 1.26], ['광진구', 1.32]]

In [24]:
df_doc = doc[doc['구별'] == '광진구']

In [25]:
df_doc[df_doc['기간'].str.contains(2018)]

TypeError: first argument must be string or compiled pattern

In [26]:
import numpy as np

In [27]:
years = np.sort(doc['기간'].unique())
cities = np.sort(doc['구별'].unique())
cities

array(['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구',
       '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
       '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'], dtype=object)

In [28]:
doc['기간'] = doc['기간'].astype(str)
years = np.sort(doc['기간'].unique())
cities = np.sort(doc['구별'].unique())
li = []
for year in years:
    for city in cities:
        df_doc = doc[doc['구별'] == city]
        doc_value = df_doc[df_doc['기간'] == str(year)]["계"].values
        te = pop[pop["기간"].str.contains(str(year))]
        pop_value = te[te['구별'] == str(city)]['인구'].mean()
        result = round((doc_value[0]/pop_value) * 100, 2)
        li.append([year, city, result])

li

[['2018', '강남구', 3.87],
 ['2018', '강동구', 1.73],
 ['2018', '강북구', 0.89],
 ['2018', '강서구', 0.94],
 ['2018', '관악구', 0.72],
 ['2018', '광진구', 1.2],
 ['2018', '구로구', 1.23],
 ['2018', '금천구', 0.85],
 ['2018', '노원구', 1.15],
 ['2018', '도봉구', 0.77],
 ['2018', '동대문구', 1.93],
 ['2018', '동작구', 1.26],
 ['2018', '마포구', 0.83],
 ['2018', '서대문구', 2.12],
 ['2018', '서초구', 2.24],
 ['2018', '성동구', 1.08],
 ['2018', '성북구', 1.11],
 ['2018', '송파구', 1.88],
 ['2018', '양천구', 1.17],
 ['2018', '영등포구', 1.9],
 ['2018', '용산구', 0.98],
 ['2018', '은평구', 0.82],
 ['2018', '종로구', 5.34],
 ['2018', '중구', 3.42],
 ['2018', '중랑구', 1.01],
 ['2019', '강남구', 4.19],
 ['2019', '강동구', 1.92],
 ['2019', '강북구', 0.97],
 ['2019', '강서구', 1.14],
 ['2019', '관악구', 0.78],
 ['2019', '광진구', 1.26],
 ['2019', '구로구', 1.36],
 ['2019', '금천구', 0.97],
 ['2019', '노원구', 1.25],
 ['2019', '도봉구', 0.85],
 ['2019', '동대문구', 1.88],
 ['2019', '동작구', 1.34],
 ['2019', '마포구', 0.89],
 ['2019', '서대문구', 2.48],
 ['2019', '서초구', 2.45],
 ['2019', '성동구', 1.21],
 ['2019', '성북구', 1.16],
 ['2019', '송파구', 1.99],
 ['2019', '양천구', 1.16],
 ['2019', '영등포구', 2.02],
 ['2019', '용산구', 1.1],
 ['2019', '은평구', 1.01],
 ['2019', '종로구', 5.79],
 ['2019', '중구', 3.26],
 ['2019', '중랑구', 1.1],
 ['2020', '강남구', 4.5],
 ['2020', '강동구', 1.88],
 ['2020', '강북구', 1.07],
 ['2020', '강서구', 1.32],
 ['2020', '관악구', 0.81],
 ['2020', '광진구', 1.32],
 ['2020', '구로구', 1.44],
 ['2020', '금천구', 1.05],
 ['2020', '노원구', 1.32],
 ['2020', '도봉구', 0.89],
 ['2020', '동대문구', 1.94],
 ['2020', '동작구', 1.38],
 ['2020', '마포구', 0.96],
 ['2020', '서대문구', 2.51],
 ['2020', '서초구', 2.65],
 ['2020', '성동구', 1.26],
 ['2020', '성북구', 1.26],
 ['2020', '송파구', 2.13],
 ['2020', '양천구', 1.22],
 ['2020', '영등포구', 2.08],
 ['2020', '용산구', 1.13],
 ['2020', '은평구', 1.09],
 ['2020', '종로구', 6.31],
 ['2020', '중구', 3.57],
 ['2020', '중랑구', 1.19]]

In [29]:
li = pd.DataFrame(li)

In [33]:
li.max()

0    2020
1     중랑구
2    6.31
dtype: object

In [34]:
ta = li[2].max()

In [35]:
re = []
for city,x in zip(li[1].values,li[2].values):
    result = (x/ta)*10
    re.append([city,round(result,2)])

In [36]:
r = pd.DataFrame(re)

In [43]:
li['합계'] = r[1]

In [45]:
li = li.rename(columns={0:"기간",1:"구별"})

In [47]:
li = li.rename(columns={2:"비율"})

In [48]:
li

      기간   구별    비율     합계
0   2018  강남구  3.87   6.13
1   2018  강동구  1.73   2.74
2   2018  강북구  0.89   1.41
3   2018  강서구  0.94   1.49
4   2018  관악구  0.72   1.14
..   ...  ...   ...    ...
70  2020  용산구  1.13   1.79
71  2020  은평구  1.09   1.73
72  2020  종로구  6.31  10.00
73  2020   중구  3.57   5.66
74  2020  중랑구  1.19   1.89

[75 rows x 4 columns]

In [49]:
li.to_csv("docPerPop_Points.csv")

In [304]:
car = pd.read_csv("NewSeoulCar.csv",index_col=1)

In [305]:
car =car.reset_index().drop("Unnamed: 0",axis=1)

In [306]:
car = car.rename(columns={"자동차 등록 합계":"합계"})

In [307]:
car = car[car['구별'] != '서울시']

In [308]:
car['기간'] = car['기간'].astype(str)

In [315]:
cities = np.sort(car['구별'].unique())

In [327]:
li = []
for city in cities:
    for year in ["2018","2019","2020"]:
        car_y = car[car['기간'].str.contains(year)]
        total = car_y[car_y['구별'] == city]['합계'].mean()
        li.append([year,city,round(total)])
li

[['2018', '강남구', 235005],
 ['2019', '강남구', 234462],
 ['2020', '강남구', 235428],
 ['2018', '강동구', 136054],
 ['2019', '강동구', 136194],
 ['2020', '강동구', 147014],
 ['2018', '강북구', 77521],
 ['2019', '강북구', 76692],
 ['2020', '강북구', 76059],
 ['2018', '강서구', 203739],
 ['2019', '강서구', 203826],
 ['2020', '강서구', 204813],
 ['2018', '관악구', 121858],
 ['2019', '관악구', 120746],
 ['2020', '관악구', 119768],
 ['2018', '광진구', 99798],
 ['2019', '광진구', 99690],
 ['2020', '광진구', 98991],
 ['2018', '구로구', 144757],
 ['2019', '구로구', 144298],
 ['2020', '구로구', 144658],
 ['2018', '금천구', 86643],
 ['2019', '금천구', 87422],
 ['2020', '금천구', 87988],
 ['2018', '노원구', 153925],
 ['2019', '노원구', 152836],
 ['2020', '노원구', 152533],
 ['2018', '도봉구', 97408],
 ['2019', '도봉구', 96932],
 ['2020', '도봉구', 96073],
 ['2018', '동대문구', 98296],
 ['2019', '동대문구', 98072],
 ['2020', '동대문구', 98080],
 ['2018', '동작구', 105233],
 ['2019', '동작구', 106028],
 ['2020', '동작구', 105528],
 ['2018', '마포구', 117630],
 ['2019', '마포구', 117778],
 ['2020', '마포구', 118812],
 ['2018', '서대문구', 86473],
 ['2019', '서대문구', 87387],
 ['2020', '서대문구', 88613],
 ['2018', '서초구', 182150],
 ['2019', '서초구', 181838],
 ['2020', '서초구', 181056],
 ['2018', '성동구', 105529],
 ['2019', '성동구', 105939],
 ['2020', '성동구', 105482],
 ['2018', '성북구', 116647],
 ['2019', '성북구', 118125],
 ['2020', '성북구', 119869],
 ['2018', '송파구', 235745],
 ['2019', '송파구', 240131],
 ['2020', '송파구', 243193],
 ['2018', '양천구', 150686],
 ['2019', '양천구', 150101],
 ['2020', '양천구', 150886],
 ['2018', '영등포구', 144317],
 ['2019', '영등포구', 142577],
 ['2020', '영등포구', 143880],
 ['2018', '용산구', 77334],
 ['2019', '용산구', 76949],
 ['2020', '용산구', 77389],
 ['2018', '은평구', 129594],
 ['2019', '은평구', 130171],
 ['2020', '은평구', 130932],
 ['2018', '종로구', 50734],
 ['2019', '종로구', 50268],
 ['2020', '종로구', 50143],
 ['2018', '중구', 52036],
 ['2019', '중구', 51772],
 ['2020', '중구', 51110],
 ['2018', '중랑구', 114092],
 ['2019', '중랑구', 113326],
 ['2020', '중랑구', 113027]]

In [328]:
df_car = pd.DataFrame(li)

In [331]:
df_car = df_car.rename(columns={0:"기간",1:"구별",2:"합계"})

In [339]:
df_car = df_car.sort_values(by="기간").reset_index().drop("index",axis=1)

In [343]:
df_car.to_csv("car.csv")

In [259]:
vv = []
for i in car['기간'].values:
    if i < 2019.01:
        x = "2018_4"
    elif i < 2019.04:
        x = "2019_1"
    elif i < 2019.07:
        x = "2019_2"
    elif i < 2019.10:
        x = "2019_3"
    elif i < 2020.01:
        x = "2019_4"
    elif i < 2020.04:
        x = "2020_1"
    elif i < 2020.07:
        x = "2020_2"
    elif i < 2020.10:
        x = "2020_3"
    else:
        x = "2020_4"
    vv.append(x)
vv

['2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2018_4',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_1',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_2',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_3',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2019_4',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_1',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_2',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_3',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4',
 '2020_4']

In [261]:
car['기간'] = vv

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [262]:
car

         기간   구별      합계
79   2018_4  종로구   50747
80   2018_4   중구   52037
81   2018_4  용산구   77456
82   2018_4  성동구  105282
83   2018_4  광진구  100029
..      ...  ...     ...
775  2020_4  관악구  119393
776  2020_4  서초구  181053
777  2020_4  강남구  236216
778  2020_4  송파구  245833
779  2020_4  강동구  149866

[675 rows x 3 columns]

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../education.csv",index_col=0)

In [6]:
df = df.rename(columns={"학급당원아수":"학급당학생수(유아)"})

In [10]:
df[df["구별"]=='종로구']['학급당학생수(유아)']

,기간,구별,원아수,학급수,학급당학생수(유아),초등학교,초등학급수,학급당학생수(초등),중학교,중등학급수,학급당학생수(중등),고등학교,고등학급수,학급당학생수(고등)
0,2018,종로구,1299,66,19.7,5507,277,19.9,2945,136,21.7,10016,373,26.9
25,2019,종로구,1217,66,18.4,5463,274,19.9,2854,135,21.1,9046,364,24.9
50,2020,종로구,1180,64,18.4,5192,269,19.3,2793,134,20.8,8467,367,23.1